=== gabrielricci/pax-playground/sdk/toolchains/arm-4.4.1/arm-none-linux-gnueabi/lib/boards/board.dtd
<!-- Board description files

     Copyright (c) 2007-2012 Mentor Graphics Corporation.

     THIS FILE CONTAINS PROPRIETARY, CONFIDENTIAL, AND TRADE
     SECRET INFORMATION OF MENTOR GRAPHICS AND/OR ITS LICENSORS.

     You may not use or distribute this file without the express
     written permission of Mentor Graphics or its authorized
     distributor.  This file is licensed only for use with 
     Sourcery CodeBench.  No other use is permitted.
     -->

<!ELEMENT board
	(category?, properties?, feature?, initialize?, memory-map?, debuggerDefaults?)>

<!-- Board category to group boards list into the tree -->
<!ELEMENT category (#PCDATA)>

<!ELEMENT properties
	(description?, property*)>

<!ELEMENT initialize
	(write-register | write-memory | delay
	 | wait-until-memory-equal | wait-until-memory-not-equal)* >
<!ELEMENT write-register EMPTY>
<!ATTLIST write-register
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        bits    CDATA   #IMPLIED>
<!ELEMENT write-memory EMPTY>
<!ATTLIST write-memory
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        bits    CDATA   #IMPLIED>
<!ELEMENT delay EMPTY>
<!ATTLIST delay
		        time CDATA   #REQUIRED>
<!ELEMENT wait-until-memory-equal EMPTY>
<!ATTLIST wait-until-memory-equal
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        timeout CDATA   #IMPLIED
                        bits    CDATA   #IMPLIED>
<!ELEMENT wait-until-memory-not-equal EMPTY>
<!ATTLIST wait-until-memory-not-equal
		        address CDATA   #REQUIRED
                        value   CDATA   #REQUIRED
                        timeout CDATA   #IMPLIED
                        bits    CDATA   #IMPLIED>

<!ELEMENT memory-map (memory-device)*>
<!ELEMENT memory-device (property*, description?, sectors*)>
<!ATTLIST memory-device
                        address CDATA   #REQUIRED
		        size    CDATA   #REQUIRED
		        type    CDATA   #REQUIRED
                        device  CDATA   #IMPLIED>

<!ELEMENT description (#PCDATA)>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ELEMENT sectors EMPTY>
<!ATTLIST sectors
	size CDATA #REQUIRED
	count CDATA #REQUIRED>

<!-- Definition of default option values for each debug interface -->
<!ELEMENT debuggerDefaults (debugInterface*)>
<!ELEMENT debugInterface (option*)>
<!ATTLIST debugInterface 
	name CDATA #REQUIRED
>
<!ELEMENT option EMPTY>
<!ATTLIST option 
	name CDATA #REQUIRED
	defaultValue CDATA #REQUIRED
>

<!ENTITY % gdbtarget SYSTEM "gdb-target.dtd">
%gdbtarget;

=== gabrielricci/pax-playground/sdk/toolchains/arm-4.4.1/arm-none-linux-gnueabi/lib/boards/zynq7000.xml
<?xml version="1.0"?>
<!DOCTYPE board SYSTEM "board.dtd">
<!-- Description for Xilinx Zynq-7000

     Version: Sourcery CodeBench Lite 2012.03-57
     Support: https://support.codesourcery.com/GNUToolchain/

     Copyright (c) 2007, 2008, 2009, 2010 CodeSourcery, Inc.

     THIS FILE CONTAINS PROPRIETARY, CONFIDENTIAL, AND TRADE SECRET
     INFORMATION OF CODESOURCERY AND/OR ITS LICENSORS.

     You may not use or distribute this file without the express written
     permission of CodeSourcery or its authorized distributor.  This file is
     licensed only for use with Sourcery CodeBench.  No other use is permitted.
     -->
<board>
  <properties>
    <description>
      Board:	Xilinx Zynq-7000
CPU:	cortexa9
    </description>
    <property name="banked-regs"/>
    <property name="has-vfp"/>
  </properties>
  <memory-map>
    <memory-device address="0x00000000" size="256M" type="ram">
      <description>
	256MB DDR SDRAM
      </description>
    </memory-device>
    <memory-device address="0xe4000000" size="64M" type="rom">
      <description>
	64MB NOR Flash Memory
      </description>
    </memory-device>
  </memory-map>
<debuggerDefaults>
<debugInterface name="mesp">
<option defaultValue="little" name="endian"/>
<option defaultValue="cortex-a9" name="cpuid"/>
<option defaultValue="${cb_install}/${cb_host}/${cb_target}/mep/tsp/arm/xilinx_zynq7000/xilinx_zynq7000_ctx-a9mp.maj" name="commandfile"/>
</debugInterface>
</debuggerDefaults>
</board>
<!-- checksum: b50f6a7f43f704a210001b08839 -->
